return {
  cmd = {
    "clangd",
    "--function-arg-placeholders",
    "-j=12",
    "--enable-config",
    "--background-index",
    "--pch-storage=memory",
    "--completion-style=detailed",
    "--limit-references=3000",
    "--limit-results=350",
    "--offset-encoding=utf-16",
    "--clang-tidy",
    "--all-scopes-completion",
    "--header-insertion=never",
    "--log=error",
  },
  filetypes = { "c", "cpp" },
  root_markers = { ".clangd", "compile_commands.json" },
  single_file_support = false,
}
